import Button from "@/components/Button";
import Admin from "@/Screen/Admin";
import Learner from "@/Screen/Learner";
import Rider from "@/Screen/Rider";
import styles from "@/styles/Home.module.css";
import { Inter } from "next/font/google";
import Head from "next/head";
import Image from "next/image";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const router = useRouter();
  const [user, setUser] = useState(null);

  const handleLogout = () => {
    localStorage.removeItem("user");
    localStorage.removeItem("token");
    router.push("/login");
  };

  useEffect(
    () => {
      const user = localStorage.getItem("user");
      if (!user) {
        router.push("login");
      }
      setUser(JSON.parse(user));
    },
    //eslint-disable-next-line
    []
  );

  if (!user) return "";

  const {
    name,
    age,
    address,
    phone,
    profilePic,
    type,
    status,
    vehicleType,
    email,
    nid,
  } = user;
  return (
    <>
      <Head>
        <title>Hero Rider | Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav className={styles.nav}>
        <Image
          height={150}
          width={150}
          className={styles.profilePic}
          src={`https://hero-rider-23.herokuapp.com/uploads/${profilePic}`}
          alt={name}
        />
        <h4>{name}</h4>
        <h4>{email}</h4>
        <Button variant="danger" onClick={handleLogout}>
          Logout
        </Button>
      </nav>
      <main className={styles.main}>
        {type !== "admin" && (
          <div>
            <h2 style={{ textAlign: "center" }}>General Info</h2>
            <h4>Name: {name}</h4>
            <h4>Email: {email}</h4>
            <h4>Age: {age}</h4>
            <h4>Phone Number: {phone}</h4>
            <h4>Address: {address}</h4>
            <h4>Vehicle Type: {vehicleType}</h4>
            <h4>Account Status: {status}</h4>
            <h4>
              NID:{" "}
              <Button>
                <a
                  target="_blank"
                  href={`https://hero-rider-23.herokuapp.com/uploads/${nid}`}
                >
                  View
                </a>
              </Button>
            </h4>
          </div>
        )}
        {type === "rider" && <Rider user={user} />}
        {type === "learner" && <Learner user={user} />}
        {type === "admin" && <Admin user={user} />}
      </main>
    </>
  );
}
